### ISSUE TITLE
Mac - SNUPI2.1 - Mg Concentration

### ISSUE THREAD

**Issue by elija-feigl** [SSDL-SNU/SNUPI#8]
using the Mac OS version of snupi 2.1. on big sur 11.4.

changing the for magnesium concentration via:
ES_MG			20
does not appear to have any effect.

electrostatics is enabled: DO_ES			1

**Comment by SSDL-SNU** [comment]
Hi, thank you for your use and report.
I checked the options for electrostatics.
But, the program correctly imported the changed Mg concentration value.
If the effect is not noticeable, there are three possible reasons.
1. The insensitive structure to electrostatic interaction: highly dense connectivity in the structure could prevent the structural deformation from the electrostatic force.
2. The low cutoff value: the default cutoff value was set to 2.5 nm, but if the interhelical distance (or distance between substructures) is larger than the cutoff value, the electrostatic interaction would not affect the deformation much.
2. The accuracy of the present model: in the present model (based on the Debye-Huckel model), the effective charge was expressed in terms of Mg concentration and based on the data for Mg 20 mM. So, the prediction for other Mg concentrations could not accurate because we do not have much structural data for different concentrations.
If you need my help more, please send me the files. I will check it.

Thank you,
Jae Young Lee

**Comment by elija-feigl** [comment]
Yes, you are correct I missed setting the cutoff value.
Apologies for erroneously reporting it as a bug. 
 
I performed a small screen for Mg concentrations from 5 to 25 with a cutoff of 5.0 nm.
Comparison with the (2.5nm cutoff - 20Mg) run showed that the resulting structure more strongly resemble the (5nm cutoff - 5Mg) run.
Qualitative comparison with experimental cryo-EM also shows significantly better agreement with the 5nm runs, and correct Mg concentration.

A note on compute time:
I tested a simple, 1033bp scaffold structure. unsurprisingly doubling the cutoff significantly affect performance.
CPU TIME (ANALYSIS)  jumped from 16 [s] to 32.17 [s].
which in my opinion it still incredibly fast :)

Based on this limited analysis I would propose a higher default value for electrostatic interaction.
what do you think?

**Comment by SSDL-SNU** [comment]
Sorry for the late reply. I did not recognize the update.
The proper cutoff distance was introduced for efficient analysis, so increasing the cutoff distance could provide a correct result.
But, increasing the cutoff distance also brings much calculation of searching interacting nodes and generating electrostatic elements, making the system heavy. 
This could especially be severe for a highly packed system. 
The current value (2.5 nm) was selected in consideration of accuracy and efficiency after analyzing many structures, so changing the default value should be careful..
But of course, you can choose the value depending on your structure/environment. 

Thank you,
Jae Young Lee

**Comment by elija-feigl** [comment]
For most of our single structure use cases a factor 2-3 in runtime hardly makes much difference.
But of course, you are right that highly packed systems might require significantly longer computation.

* I now use 3.75nm electrostatics cutoff as my default.
* If faster computation is required I reduce the cutoff to the default value of 2.5nm

best, elija

**Comment by SSDL-SNU** [comment]
Thank you for your trials and opinion. The effects of the electrostatic parameters including cutoff are of importance and interest. Your report is surely helpful for future improvement. 

Thank you, 
Jae Young
